%let EM_PROJECT =;
%let EM_PROJECTNAME =;
%let EM_WSNAME =;
%let EM_WSDESCRIPTION =;
%let EM_SUMMARY =WORK.SUMMARY;
%let EM_NUMTASKS =SINGLE;
%let EM_EDITMODE =R;
%let EM_DEBUGVAL =;
%let EM_ACTION =run;
*------------------------------------------------------------*;
* Create workspace data set + update;
*------------------------------------------------------------*;
data workspace;
length property $64 value $100;
property= 'PROJECTLOCATION';
value= "&EM_PROJECT";
output;
property= 'PROJECTNAME';
value= "&EM_PROJECTNAME";
output;
property= 'WORKSPACENAME';
value= "&EM_WSNAME";
output;
property= 'WORKSPACEDESCRIPTION';
value= "&EM_WSDESCRIPTION";
output;
property= 'SUMMARYDATASET';
value= "&EM_SUMMARY";
output;
property= 'NUMTASKS';
value= "&EM_NUMTASKS";
output;
property= 'EDITMODE';
value= "&EM_EDITMODE";
output;
property= 'DEBUG';
value= "&EM_DEBUGVAL";
output;
run;
*------------------------------------------------------------*;
* Create nodes data set;
*------------------------------------------------------------*;
data nodes;
length id $12 component $32 description $64 X 8 Y 8 diagramID $32 parentID $32;
id= "Score";
component="Score";
description= "Score";
diagramID="_ROOT_";
parentID="";
X=570;
Y=169;
output;
id= "Reg";
component="Regression";
description= "Regression";
diagramID="_ROOT_";
parentID="";
X=344;
Y=170;
output;
id= "Ids";
component="DataSource";
description= "HMEQ_TRAIN";
diagramID="_ROOT_";
parentID="";
X=143;
Y=165;
output;
run;
*------------------------------------------------------------*;
* DataSource Properties;
*------------------------------------------------------------*;
data WORK.homeequity_P;
  length   Property                         $ 32
           Value                            $ 200
           ;

Property="Name";
Value="homeequity";
output;
Property="CreateDate";
Value="1611065730.6";
output;
Property="ModifyDate";
Value="1611065840.2";
output;
Property="CreatedBy";
Value="mdlmgradmin";
output;
Property="ModifiedBy";
Value="mdlmgradmin";
output;
Property="SampleSizeType";
Value="";
output;
Property="SampleSize";
Value="";
output;
;
run;
*------------------------------------------------------------*;
* EMNOTES File for Score;
*------------------------------------------------------------*;
data _null_;
if symget('sysscp')=:'WIN' then dsep='\';
else if symget('sysscp')=:'DNT' then dsep='\';
else dsep = '/';
filepath = pathname('work')!!dsep!!"Score_EMNOTES.txt";
call symput('DSPATH', filepath);
run;
data _null_;
filename dspath "&dspath" encoding="utf-8" NOBOM;
file dspath;
run;
*------------------------------------------------------------*;
* Decmeta Data Set for Reg;
*------------------------------------------------------------*;
data WORK.Reg_BAD_DM;
  length   _TYPE_                           $ 32
           VARIABLE                         $ 32
           LABEL                            $ 40
           LEVEL                            $ 32
           EVENT                            $ 32
           ORDER                            $ 10
           FORMAT                           $ 32
           TYPE                             $ 1
           COST                             $ 32
           USE                              $ 1
           ;

  label    _TYPE_="Type"
           VARIABLE="Variable"
           LABEL="Label"
           LEVEL="Measurement Level"
           EVENT="Target Event"
           ORDER="Order"
           FORMAT="Format"
           TYPE="Type"
           COST="Cost"
           USE="Use"
           ;
_TYPE_="MATRIX";
VARIABLE="";
LABEL="";
LEVEL="PROFIT";
EVENT="";
ORDER="";
FORMAT="";
TYPE="";
COST="";
USE="N";
output;
_TYPE_="TARGET";
VARIABLE="BAD";
LABEL="";
LEVEL="BINARY";
EVENT="1";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="";
output;
_TYPE_="DECISION";
VARIABLE="DECISION1";
LABEL="1";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="Y";
output;
_TYPE_="DECISION";
VARIABLE="DECISION2";
LABEL="0";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="Y";
output;
_TYPE_="DATAPRIOR";
VARIABLE="DATAPRIOR";
LABEL="Data Prior";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="N";
output;
_TYPE_="TRAINPRIOR";
VARIABLE="TRAINPRIOR";
LABEL="Training Prior";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="N";
output;
_TYPE_="DECPRIOR";
VARIABLE="DECPRIOR";
LABEL="Decision Prior";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="N";
output;
_TYPE_="PREDICTED";
VARIABLE="P_BAD1";
LABEL="Predicted: BAD=1";
LEVEL="1";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="";
output;
_TYPE_="RESIDUAL";
VARIABLE="R_BAD1";
LABEL="Residual: BAD=1";
LEVEL="1";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="";
output;
_TYPE_="PREDICTED";
VARIABLE="P_BAD0";
LABEL="Predicted: BAD=0";
LEVEL="0";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="";
output;
_TYPE_="RESIDUAL";
VARIABLE="R_BAD0";
LABEL="Residual: BAD=0";
LEVEL="0";
EVENT="";
ORDER="";
FORMAT="";
TYPE="N";
COST="";
USE="";
output;
_TYPE_="FROM";
VARIABLE="F_BAD";
LABEL="From: BAD";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="C";
COST="";
USE="";
output;
_TYPE_="INTO";
VARIABLE="I_BAD";
LABEL="Into: BAD";
LEVEL="";
EVENT="";
ORDER="";
FORMAT="";
TYPE="C";
COST="";
USE="";
output;
;
run;
*------------------------------------------------------------*;
* Decdata Data Set for Reg;
*------------------------------------------------------------*;
data WORK.Reg_BAD_DD(label="BAD");
  length   BAD                              $ 32
           COUNT                              8
           DATAPRIOR                          8
           TRAINPRIOR                         8
           DECPRIOR                           8
           DECISION1                          8
           DECISION2                          8
           ;

  label    COUNT="Level Counts"
           DATAPRIOR="Data Proportions"
           TRAINPRIOR="Training Proportions"
           DECPRIOR="Decision Priors"
           DECISION1="1"
           DECISION2="0"
           ;
BAD="1";
COUNT=1189;
DATAPRIOR=0.1994966442953;
TRAINPRIOR=0.1994966442953;
DECPRIOR=.;
DECISION1=1;
DECISION2=0;
output;
BAD="0";
COUNT=4771;
DATAPRIOR=0.80050335570469;
TRAINPRIOR=0.80050335570469;
DECPRIOR=.;
DECISION1=0;
DECISION2=1;
output;
;
run;
*------------------------------------------------------------*;
* EMNOTES File for Reg;
*------------------------------------------------------------*;
data _null_;
if symget('sysscp')=:'WIN' then dsep='\';
else if symget('sysscp')=:'DNT' then dsep='\';
else dsep = '/';
filepath = pathname('work')!!dsep!!"Reg_EMNOTES.txt";
call symput('DSPATH', filepath);
run;
data _null_;
filename dspath "&dspath" encoding="utf-8" NOBOM;
file dspath;
run;
*------------------------------------------------------------*;
* Variable Attributes for Ids;
*------------------------------------------------------------*;
data WORK.Ids_VariableAttribute;
length Variable $64 AttributeName $32 AttributeValue $64;
Variable='BAD';
AttributeName="ROLE";
AttributeValue='TARGET';
Output;
Variable='BAD';
AttributeName="LEVEL";
AttributeValue='BINARY';
Output;
Variable='DEBTINC';
AttributeName="REPORT";
AttributeValue='Y';
Output;
run;
*------------------------------------------------------------*;
* EMNOTES File for Ids;
*------------------------------------------------------------*;
data _null_;
if symget('sysscp')=:'WIN' then dsep='\';
else if symget('sysscp')=:'DNT' then dsep='\';
else dsep = '/';
filepath = pathname('work')!!dsep!!"Ids_EMNOTES.txt";
call symput('DSPATH', filepath);
run;
data _null_;
filename dspath "&dspath" encoding="utf-8" NOBOM;
file dspath;
run;
*------------------------------------------------------------*;
* Create node properties data set;
*------------------------------------------------------------*;
data nodeprops;
length id $12 property $64 value $64;
id= "Score";
property="OutputType";
value= "VIEW";
output;
id= "Score";
property="FixedOutputNames";
value= "Y";
output;
id= "Score";
property="HideVariables";
value= "N";
output;
id= "Score";
property="HideInput";
value= "Y";
output;
id= "Score";
property="HideTarget";
value= "Y";
output;
id= "Score";
property="HideRejected";
value= "Y";
output;
id= "Score";
property="HideAssess";
value= "Y";
output;
id= "Score";
property="HidePredict";
value= "Y";
output;
id= "Score";
property="HideFreq";
value= "Y";
output;
id= "Score";
property="HideClassification";
value= "Y";
output;
id= "Score";
property="HideResidual";
value= "Y";
output;
id= "Score";
property="HideOther";
value= "Y";
output;
id= "Score";
property="ScoreValidate";
value= "N";
output;
id= "Score";
property="ScoreTest";
value= "N";
output;
id= "Score";
property="CScore";
value= "Y";
output;
id= "Score";
property="JScore";
value= "Y";
output;
id= "Score";
property="PackageName";
value= "DEFAULT";
output;
id= "Score";
property="UserPackageName";
value= "";
output;
id= "Score";
property="PreferenceName";
value= "";
output;
id= "Score";
property="OptimizedCode";
value= "Y";
output;
id= "Score";
property="GraphReports";
value= "Y";
output;
id= "Score";
property="ForceRun";
value= "N";
output;
id= "Score";
property="RunAction";
value= "Train";
output;
id= "Score";
property="Component";
value= "Score";
output;
id= "Score";
property="EM_FILE_EMNOTES";
value= "Score_EMNOTES.txt";
output;
id= "Reg";
property="MainEffect";
value= "Y";
output;
id= "Reg";
property="TwoFactor";
value= "N";
output;
id= "Reg";
property="Polynomial";
value= "N";
output;
id= "Reg";
property="PolynomialDegree";
value= "2";
output;
id= "Reg";
property="Terms";
value= "N";
output;
id= "Reg";
property="Error";
value= "LOGISTIC";
output;
id= "Reg";
property="LinkFunction";
value= "LOGIT";
output;
id= "Reg";
property="SuppressIntercept";
value= "N";
output;
id= "Reg";
property="InputCoding";
value= "DEVIATION";
output;
id= "Reg";
property="MinResourceUse";
value= "N";
output;
id= "Reg";
property="ModelSelection";
value= "NONE";
output;
id= "Reg";
property="SelectionCriterion";
value= "DEFAULT";
output;
id= "Reg";
property="SelectionDefault";
value= "Y";
output;
id= "Reg";
property="Sequential";
value= "N";
output;
id= "Reg";
property="SlEntry";
value= "0.05";
output;
id= "Reg";
property="SlStay";
value= "0.05";
output;
id= "Reg";
property="Start";
value= "0";
output;
id= "Reg";
property="Stop";
value= "0";
output;
id= "Reg";
property="Force";
value= "0";
output;
id= "Reg";
property="Hierarchy";
value= "CLASS";
output;
id= "Reg";
property="Rule";
value= "NONE";
output;
id= "Reg";
property="MaxStep";
value= ".";
output;
id= "Reg";
property="StepOutput";
value= "N";
output;
id= "Reg";
property="OptimizationTechnique";
value= "DEFAULT";
output;
id= "Reg";
property="ModelDefaults";
value= "Y";
output;
id= "Reg";
property="MaxIterations";
value= ".";
output;
id= "Reg";
property="MaxFunctionCalls";
value= ".";
output;
id= "Reg";
property="MaxCPUTime";
value= "1 HOUR";
output;
id= "Reg";
property="ConvDefaults";
value= "Y";
output;
id= "Reg";
property="AbsConvValue";
value= "-1.34078E154";
output;
id= "Reg";
property="AbsFValue";
value= "0";
output;
id= "Reg";
property="AbsFTime";
value= "1";
output;
id= "Reg";
property="AbsGValue";
value= "0.00001";
output;
id= "Reg";
property="AbsGTime";
value= "1";
output;
id= "Reg";
property="AbsXValue";
value= "1E-8";
output;
id= "Reg";
property="AbsXTime";
value= "1";
output;
id= "Reg";
property="FConvValue";
value= "0";
output;
id= "Reg";
property="FConvTimes";
value= "1";
output;
id= "Reg";
property="GConvValue";
value= "1E-6";
output;
id= "Reg";
property="GConvTimes";
value= "1";
output;
id= "Reg";
property="ClParm";
value= "N";
output;
id= "Reg";
property="Covout";
value= "N";
output;
id= "Reg";
property="CovB";
value= "N";
output;
id= "Reg";
property="CorB";
value= "N";
output;
id= "Reg";
property="Simple";
value= "N";
output;
id= "Reg";
property="SuppressOutput";
value= "N";
output;
id= "Reg";
property="Details";
value= "N";
output;
id= "Reg";
property="PrintDesignMatrix";
value= "N";
output;
id= "Reg";
property="SASSPDS";
value= "N";
output;
id= "Reg";
property="Performance";
value= "N";
output;
id= "Reg";
property="ExcludedVariable";
value= "REJECT";
output;
id= "Reg";
property="ForceRun";
value= "N";
output;
id= "Reg";
property="RunAction";
value= "Train";
output;
id= "Reg";
property="Component";
value= "Regression";
output;
id= "Reg";
property="EM_DECMETA_BAD";
value= "WORK.Reg_BAD_DM";
output;
id= "Reg";
property="EM_DECDATA_BAD";
value= "WORK.Reg_BAD_DD";
output;
id= "Reg";
property="EM_FILE_EMNOTES";
value= "Reg_EMNOTES.txt";
output;
id= "Ids";
property="DataSource";
value= "homeequity";
output;
id= "Ids";
property="Scope";
value= "LOCAL";
output;
id= "Ids";
property="Role";
value= "TRAIN";
output;
id= "Ids";
property="Library";
value= "SAMPSIO";
output;
id= "Ids";
property="Table";
value= "HMEQ";
output;
id= "Ids";
property="NCols";
value= "13";
output;
id= "Ids";
property="NObs";
value= "5960";
output;
id= "Ids";
property="NBytes";
value= "640000";
output;
id= "Ids";
property="Segment";
value= "";
output;
id= "Ids";
property="DataSourceRole";
value= "TRAIN";
output;
id= "Ids";
property="OutputType";
value= "VIEW";
output;
id= "Ids";
property="ForceRun";
value= "N";
output;
id= "Ids";
property="ComputeStatistics";
value= "N";
output;
id= "Ids";
property="DataSelection";
value= "DATASOURCE";
output;
id= "Ids";
property="NewTable";
value= " ";
output;
id= "Ids";
property="MetaAdvisor";
value= "BASIC";
output;
id= "Ids";
property="ApplyIntervalLevelLowerLimit";
value= "Y";
output;
id= "Ids";
property="IntervalLowerLimit";
value= "20";
output;
id= "Ids";
property="ApplyMaxPercentMissing";
value= "Y";
output;
id= "Ids";
property="MaxPercentMissing";
value= "50";
output;
id= "Ids";
property="ApplyMaxClassLevels";
value= "Y";
output;
id= "Ids";
property="MaxClassLevels";
value= "20";
output;
id= "Ids";
property="IdentifyEmptyColumns";
value= "Y";
output;
id= "Ids";
property="VariableValidation";
value= "STRICT";
output;
id= "Ids";
property="NewVariableRole";
value= "REJECT";
output;
id= "Ids";
property="DropMapVariables";
value= "Y";
output;
id= "Ids";
property="DsId";
value= "homeequity";
output;
id= "Ids";
property="DsSampleName";
value= "";
output;
id= "Ids";
property="DsSampleSizeType";
value= "";
output;
id= "Ids";
property="DsSampleSize";
value= "";
output;
id= "Ids";
property="DsCreatedBy";
value= "mdlmgradmin";
output;
id= "Ids";
property="DsCreateDate";
value= "1611065730.6";
output;
id= "Ids";
property="DsModifiedBy";
value= "mdlmgradmin";
output;
id= "Ids";
property="DsModifyDate";
value= "1611065840.2";
output;
id= "Ids";
property="DsScope";
value= "LOCAL";
output;
id= "Ids";
property="Sample";
value= "D";
output;
id= "Ids";
property="SampleSizeType";
value= "PERCENT";
output;
id= "Ids";
property="SampleSizePercent";
value= "20";
output;
id= "Ids";
property="SampleSizeObs";
value= "10000";
output;
id= "Ids";
property="DBPassThrough";
value= "Y";
output;
id= "Ids";
property="RunAction";
value= "Train";
output;
id= "Ids";
property="Component";
value= "DataSource";
output;
id= "Ids";
property="Description";
value= "";
output;
id= "Ids";
property="EM_VARIABLEATTRIBUTES";
value= "WORK.Ids_VariableAttribute";
output;
id= "Ids";
property="EM_FILE_EMNOTES";
value= "Ids_EMNOTES.txt";
output;
run;
*------------------------------------------------------------*;
* Create connections data set;
*------------------------------------------------------------*;
data connect;
length from to $12;
from="Reg";
to="Score";
output;
from="Ids";
to="Reg";
output;
run;
*------------------------------------------------------------*;
* Create actions to run data set;
*------------------------------------------------------------*;
%macro emaction;
%let actionstring = %upcase(&EM_ACTION);
%if %index(&actionstring, RUN) or %index(&actionstring, REPORT) %then %do;
data actions;
length id $12 action $40;
id="Score";
%if %index(&actionstring, RUN) %then %do;
action='run';
output;
%end;
%if %index(&actionstring, REPORT) %then %do;
action='report';
output;
%end;
run;
%end;
%mend;
%emaction;
*------------------------------------------------------------*;
* Execute the actions;
*------------------------------------------------------------*;
%em5batch(execute, workspace=workspace, nodes=nodes, connect=connect, datasources=datasources, nodeprops=nodeprops, action=actions);
