data sasep.out;
  dcl package score sc();
  dcl double "LOAN";
  dcl double "VALUE";
  dcl double "MORTDUE";
  dcl double "YOJ";
  dcl double "DEROG";
  dcl double "DELINQ";
  dcl double "CLAGE";
  dcl double "NINQ";
  dcl double "CLNO";
  dcl double "DEBTINC";
  dcl nchar(7) "JOB";
  dcl nchar(7) "REASON";
  dcl double "P_BAD1" having label n'Predicted: BAD=1';
  dcl double "P_BAD0" having label n'Predicted: BAD=0';
  dcl nchar(32) "I_BAD" having label n'Into: BAD';
  dcl nchar(4) "_WARN_" having label n'Warnings';
  varlist allvars[_all_];
  method init();
    sc.setvars(allvars);
    sc.setKey(n'701FA927F8894721E1346630744ECD653C93AAAA');
  end;
  method preScoreRecord();
  end;
  method postScoreRecord();
  end;
  method term();
  end;
  method run();
    set sasep.in;
    preScoreRecord();
    sc.scoreRecord();
    postScoreRecord();
  end;
enddata;
